import DOMPurify from 'dompurify';

// Force every surviving <a> to open safely: drop unsafe schemes (only
// http/https/mailto links keep their href) and always set
// rel="noopener noreferrer" + target="_blank". Registered once at module load.
let hookRegistered = false;
function registerLinkHook(): void {
  if (hookRegistered) return;
  hookRegistered = true;
  DOMPurify.addHook('afterSanitizeAttributes', (node) => {
    if (node.nodeName !== 'A') return;
    const el = node as Element;
    const href = el.getAttribute('href');
    // Keep only http(s)/mailto links; strip anything else (e.g. residual
    // javascript:, data:, relative scheme tricks) defensively.
    if (href && !/^(?:https?:|mailto:)/i.test(href.trim())) {
      el.removeAttribute('href');
    }
    el.setAttribute('rel', 'noopener noreferrer');
    el.setAttribute('target', '_blank');
  });
}

/**
 * Sanitizes HTML content to prevent XSS attacks.
 * Only allows safe tags generated by TipTap/RichTextEditor.
 */
export function sanitizeHTML(dirty: string | null | undefined): string {
  if (!dirty) return '';

  registerLinkHook();

  return DOMPurify.sanitize(dirty, {
    ALLOWED_TAGS: [
      'p',
      'br',
      'strong',
      'em',
      'u',
      's',
      'strike',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'ul',
      'ol',
      'li',
      'blockquote',
      'mark',
      'code',
      'pre',
      'div',
      'span',
      'a',
      'hr',
    ],
    ALLOWED_ATTR: ['class', 'href', 'target', 'rel'],
    ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto):|[^a-z]|[a-z+.-]+(?:[^a-z+.\-:]|$))/i,
    ALLOW_DATA_ATTR: false,
    // Force all links to open safely
    ADD_ATTR: ['target', 'rel'],
    FORBID_TAGS: ['script', 'iframe', 'object', 'embed', 'form', 'input'],
    FORBID_ATTR: ['onerror', 'onclick', 'onload', 'onmouseover'],
  });
}
