import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { CheckCircle, Eye, Edit, Share, Bot, FileText } from "lucide-react";
import { Link } from "react-router-dom";

interface ContractSuccessProps {
  contract: {
    id: string;
    title: string;
    status: string;
    contract_type?: string;
  };
  onViewContract: () => void;
}

export function ContractSuccess({ contract, onViewContract }: ContractSuccessProps) {
  return (
    <div className="flex items-center justify-center min-h-[60vh] p-6">
      <Card className="w-full max-w-2xl shadow-lg">
        <CardHeader className="text-center pb-4">
          <div className="mx-auto w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mb-4">
            <CheckCircle className="h-8 w-8 text-green-600" />
          </div>
          <CardTitle className="text-2xl text-green-700">Contract Successfully Generated!</CardTitle>
          <p className="text-muted-foreground mt-2">
            Your contract has been created using AI and is ready for review.
          </p>
        </CardHeader>
        
        <CardContent className="space-y-6">
          {/* Contract Preview */}
          <div className="bg-muted/30 p-4 rounded-lg border">
            <div className="flex items-start justify-between">
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <FileText className="h-5 w-5 text-primary" />
                  <h3 className="font-semibold">{contract.title}</h3>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                    {contract.status}
                  </Badge>
                  <Badge variant="secondary" className="bg-blue-50 text-blue-700 border-blue-200">
                    <Bot className="h-3 w-3 mr-1" />
                    AI Generated
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  Type: {contract.contract_type || 'Contract'}
                </p>
                <code className="text-xs bg-muted px-2 py-1 rounded font-mono">
                  ID: {contract.id}
                </code>
              </div>
            </div>
          </div>

          {/* Important Notice */}
          <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
            <div className="flex items-start gap-3">
              <div className="w-5 h-5 bg-amber-100 rounded-full flex items-center justify-center flex-shrink-0">
                <span className="text-amber-600 text-sm font-bold">!</span>
              </div>
              <div>
                <h4 className="font-medium text-amber-800 mb-1">Review Required</h4>
                <p className="text-sm text-amber-700">
                  This contract was generated by AI and should be reviewed by legal counsel before use. 
                  Please verify all terms, conditions, and details are accurate.
                </p>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-3">
            <Button 
              onClick={onViewContract}
              className="flex-1 h-11"
            >
              <Eye className="h-4 w-4 mr-2" />
              View & Review Contract
            </Button>
            
            <div className="flex gap-2 flex-1">
              <Button variant="outline" className="flex-1" asChild>
                <Link to={`/contracts/${contract.id}/edit`}>
                  <Edit className="h-4 w-4 mr-2" />
                  Edit
                </Link>
              </Button>
              
              <Button variant="outline" className="flex-1">
                <Share className="h-4 w-4 mr-2" />
                Share
              </Button>
            </div>
          </div>

          {/* Quick Actions */}
          <div className="pt-4 border-t">
            <p className="text-sm text-muted-foreground mb-3">Quick Actions:</p>
            <div className="flex flex-wrap gap-2">
              <Button variant="ghost" size="sm" asChild>
                <Link to="/contracts/create">
                  Create Another Contract
                </Link>
              </Button>
              <Button variant="ghost" size="sm" asChild>
                <Link to="/contracts">
                  Back to Contracts
                </Link>
              </Button>
              <Button variant="ghost" size="sm" asChild>
                <Link to={`/ream-ai?contract=${contract.id}`}>
                  <Bot className="h-3 w-3 mr-1" />
                  AI Analysis
                </Link>
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}